---
exclude_paths:
  - .cache/ # implicit unless exclude_paths is defined in config
  - .config/
  - .git/
  - .github/
  - .gitlab/
  - .vscode/
  - .venv/
  - .env/
  - .tox/
  - tests/
exclude_files:
  - .ansible-lint.yaml
  - galaxy.yml
